CREATE TABLE IF NOT EXISTS posts (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	parent INTEGER,
	time DATETIME DEFAULT CURRENT_TIMESTAMP,
	ip TEXT,
	name TEXT,
	email TEXT,
	subject TEXT,
	content TEXT,
	replies INTEGER DEFAULT 0,
	frozen INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS bans (
	ip TEXT NOT NULL,
	why TEXT
);